### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by VolodymyrYavorskyi** [VolodymyrYavorskyi/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by VolodiaYavorskyi** [comment]
- I am Neo, a cybercriminal and computer programmer. Some people call me "The One who would bring peace." I don't know the reason, but what I definitely know - I will be a superhero.
