### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by VolodymyrYavorskyi** [VolodymyrYavorskyi/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by VolodiaYavorskyi** [comment]
https://www.imdb.com/title/tt0133093/characters/nm0000206?ref_=tt_cl_t1
https://www.instagram.com/neomatrixbrave/?hl=en
https://twitter.com/neofromthematr2
https://www.pinterest.com/bleeneo101/neo-in-the-matrix/
