### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by VolodymyrYavorskyi** [VolodymyrYavorskyi/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by VolodiaYavorskyi** [comment]
# Main achievements
### Before the Matrix

- In high school, I excelled at science, math, and computer courses
- Penetrated computer systems illicitly and stole information
- Sold illegal untraceable computer systems and hacking programs along with controlling computer viruses

### The Matrix

- Took the ["red pill"](https://en.wikipedia.org/wiki/Red_pill)
- Entered the Matrix
- Dodged bullets in an [incredible manner](https://media0.giphy.com/media/eIm624c8nnNbiG0V3g/giphy.gif?cid=790b7611ef6937afb5c5ff0132fdb70b466191f5c0526d63&rid=giphy.gif&ct=g)
- Rescued Morpheus
- Didn't save the world :disappointed:

### The Matrix Reloaded

- Found cool [coat](https://ae01.alicdn.com/kf/Hba56fc1ea87a44e7b0ec2991bf2ef991r/Matrix-Cosplay-Customised-Black-Cosplay-Costume-Neo-Trench-Coat-Only-Coat-Halloween-cosplay-Costume-free-shipping.png)
- Rescued the Keymaker
- Met the Architect
- Still didn't save the world :disappointed:

### The Matrix Revolutions

- Learned everything about the Matrix
- Defeated agent Smith
- Got blind
- Finally saved the world :relieved:
